language: node_js
node_js:
- '0.11'
services:
- redis-server
- mongodb
before_install:
- npm install -d
script:
- NODE_ENV=test gulp test
notifications:
  hipchat:
    rooms:
      secure: SipvTAaiyl3GVrL0Nd+GF72CQfGQWmouGRTCCxaR/4Lro0MEraRkS3L5qFruxg70ATWlZA0VFXBrgmIQhlj1F5RKn/BOZmGRM2ybvaLvUc6Ao3VNPq8slaZNCDQnyL0CrpvYpNGIZwrs9ICy31M+c4ypw4UzkmJ4jHkqmddCCKw=
