language: node_js
node_js:
- '0.10'
- '0.11'
services:
- redis-server
script: "npm run-script test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
notifications:
  hipchat:
    rooms:
      secure: SipvTAaiyl3GVrL0Nd+GF72CQfGQWmouGRTCCxaR/4Lro0MEraRkS3L5qFruxg70ATWlZA0VFXBrgmIQhlj1F5RKn/BOZmGRM2ybvaLvUc6Ao3VNPq8slaZNCDQnyL0CrpvYpNGIZwrs9ICy31M+c4ypw4UzkmJ4jHkqmddCCKw=
